import Head from "next/head"
import Image from "next/image"

export default function Home() {
  
  return (
    <div className="bg-white scroll-smooth min-w-full">
      <Head>
        <title>Cardine design</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <a href="#top">
      <div className="fixed bottom-0 right-0 mb-20 mr-5 hover:animate-pops active:animate-pops">
      <img
        src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dd48921b55349f4f0f5f0f_Group%20124%20(3).png"
        alt="image"
        width={50}
        height={40} />
      </div>
      </a>
      <div className="flex flex-row justify-between px-2 sm:px-2 py-5
      bg-[url('https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dbd808c4621625592cbebd_Group%20138.png')]
      bg-no-repeat bg-cover" id="top">
        <div className="flex flex-row items-center justify-between space-x-5">
          <div className="flex flex-row items-center sm:mx-4">
          <img
            src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dffcc83e564f8d5faff972_IMG_9857%201%20(1).png"
            alt="image"
            width={70}
            height={60} />
            <a
              href="https://drive.google.com/file/d/1bImFYYpU79knglIEJAuIuV4QzpWJEfFG/view?usp=sharing"
              className="text-gray-800 font-semibold">Resumé</a>
          </div>
            <a 
              href="mailto:dcardinesiii@gmail.com?subject=Hey%20Dante!"
              className="text-gray-800 font-semibold border border-gray-800 py-3 px-9 sm:px-3  md:px-9
              rounded-3xl whitespace-nowrap">Get in touch!</a>
        </div>
        <div className="flex flex-row items-center">
          <div className="sm:flex flex-row items-center space-x-5 hidden">
            <a href="#" className="text-gray-800 font-semibold whitespace-nowrap">Check out my</a>
            <a href="https://www.linkedin.com/authwall?trk=gf&trkInfo=AQGBM2NDtRnZTgAAAX-3jbXAbP6YAav-ZRohwebBy8BavOmOYjtRm
              VxZX1P3BhhU0C2ZQyGpONIFoIfPoI0v3yB-6_s4cS-Cn1xTw6Xpe26b3X4cSvss0VGyDaZwa3rWmgCPBWY=&originalReferer=https://www
              .cardines.design/&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fdcardines%2F"
              target="_blank" rel="noreferrer">
              <img
              src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dfbf3729e13cebb7fa9042_linkedin.svg"
              alt="image"
              width={40}
              height={50} />
            </a>
            <a href="https://dribbble.com/dcardines" target="_blank" rel="noreferrer">
              <img
              src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dfbf37cbbc7f39501d8299_dribbble.svg"
              alt="image"
              width={40}
              height={50} />
            </a>
            <a href="https://www.behance.net/dcardines" target="_blank" rel="noreferrer">
              <img
              src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dfbf374e1ac4f7d87ecc33_behance.svg"
              alt="image"
              width={40}
              height={50} />
            </a>
          </div>
          </div>
        </div>
        <div className="flex flex-col items-center sm:hidden">
          <a href="#" className="text-gray-800 font-semibold mb-5">Check out my</a>
          <div className="flex flex-row space-x-5">
            <a href="https://www.linkedin.com/authwall?trk=gf&trkInfo=AQGBM2NDtRnZTgAAAX-3jbXAbP6YAav-ZRohwebBy8BavOmOYjtRm
              VxZX1P3BhhU0C2ZQyGpONIFoIfPoI0v3yB-6_s4cS-Cn1xTw6Xpe26b3X4cSvss0VGyDaZwa3rWmgCPBWY=&originalReferer=https://www
              .cardines.design/&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fdcardines%2F"
              target="_blank" rel="noreferrer">
              <img
              src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dfbf3729e13cebb7fa9042_linkedin.svg"
              alt="image"
              width={40}
              height={50} />
            </a>
            <a href="https://dribbble.com/dcardines" target="_blank" rel="noreferrer">
              <img
              src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dfbf37cbbc7f39501d8299_dribbble.svg"
              alt="image"
              width={40}
              height={50} />
            </a>
            <a href="https://www.behance.net/dcardines" target="_blank" rel="noreferrer">
              <img
              src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dfbf374e1ac4f7d87ecc33_behance.svg"
              alt="image"
              width={40}
              height={50} />
            </a>
          </div>
        </div>
        <div className="flex sm:flex-row flex-col items-center justify-between sm:-mt-40 sm:mx-24 p-10 bg-no-repeat bg-contain
          bg-[url('https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dbd45d2cf9fa0fd530101c_Group%209-p-500.png')] sm:bg-none">
        <img
          className="animate-slowloadpop hover:animate-pops -ml-32 sm:ml-0"
          src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61e001f928dbf46249f45a1b_Frame%207-p-500.png"
          alt="image"
          width={350}
          height={350} />
        <img
          className="sm:mt-60 animate-slowloadpop hover:animate-pops -mr-32 sm:mr-0"
          src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61e001f946b7dd516da364df_Frame%206-p-500.png"
          alt="image"
          width={350}
          height={350} />
        </div>
        <div className="flex sm:flex-row flex-col items-center justify-center sm:-mt-96 -mt-96 sm:visible invisible">
          <img
            className="sm:mt-40 animate-slowloadpop hover:animate-pop -mt-24"
            src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dbd45d2cf9fa0fd530101c_Group%209-p-500.png"
            alt="image"
            width={350}
            height={350} />
        </div>
        <div className="flex sm:flex-row flex-col items-center justify-between sm:-mt-96 sm:ml-20">
        <img
          className="animate-slowloadpop hover:animate-pops"
          src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61e001f9552e82b83020e0f9_Frame%203-p-500.png"
          alt="image"
          width={350}
          height={350} />
        <img
          className="sm:mt-40 hover:animate-pops animate-slowpops mr-48"
          src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61e001f922a500f6571ffd6b_Frame%202-p-500.png"
          alt="image"
          width={250}
          height={350} />
        </div>
        <div className="flex sm:flex-row flex-col items-center justify-between sm:-mt-60 mx-20">
        <img
          className="animate-slowloadpop hover:animate-pops sm:mt-32 ml-48"
          src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61e001f97ae68c5def120780_Frame%20100-p-500.png"
          alt="image"
          width={350}
          height={350} />
        <img
          className="sm:mt-40 animate-slowloadpop hover:animate-pops mr-48"
          src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61e001f93e564ff3e1b012b6_Frame%2099-p-500.png"
          alt="image"
          width={350}
          height={350} />
        </div>
        <div className="flex flex-col items-center justify-center sm:-mt-48 -mt-54 mx-20">
        <img
          className="animate-pops sm:mt-32"
          src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dcfb29c8725abbd9421974_Group%2097%20(2).png"
          alt="image"
          width={35}
          height={35} />
        <img
          className="sm:mt-10 animate-slowloadpop hover:animate-pops"
          src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61e001f975e2cca89bcbfa96_Frame%209-p-500.png"
          alt="image"
          width={350}
          height={350} />
        </div>
        <div className="bg-gray-100 mt-10 py-10 px-5">
          <div className="flex flex-row items-center ml-10">
            <h1 className="text-3xl font-semibold">Work</h1>
            <img
              className="hover:animate-wiggle"
              src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61e00c2abb525b14ce29f484_%F0%9F%93%9D.png"
              width={50}
              height={50} />
          </div>
          <div className="sm:grid sm:grid-cols-2 md:grid-cols-3 flex flex-col gap-10 my-10 ml-10">
            <div className="cards">
              <a href="https://www.cardines.design/work/selnara">
                <Image
                  className="rounded-md hover:opacity-90"
                  layout="intrinsic"
                  src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dbfc0346c2a74882afec92_Selnara%20Main-p-1600.jpeg"
                  alt="image"
                  width={350}
                  height={250}
                />
                <h2 className="text-xl text-black font-semibold">Selnara</h2>
                <p className="text-gray-700 font-semibold">Product Design, No-Code Dev & Illustration</p>
              </a>
            </div>
            <div className="cards">
              <a href="https://www.cardines.design/work/project-5">
                <Image
                  className="rounded-md hover:opacity-90"
                  layout="intrinsic"
                  src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dbfc034b43be6beb563923_Fitness-First-Hero-p-1080.jpeg"
                  alt="image"
                  width={350}
                  height={250}
                />
                <h2 className="text-xl text-black font-semibold">MyFit Plan</h2>
                <p className="text-gray-700 font-semibold">UI/UX</p>
              </a>
            </div>
            <div className="cards">
              <a href="https://www.cardines.design/work/tara-na">
                <Image
                  className="rounded-md hover:opacity-90"
                  layout="intrinsic"
                  src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dbfc037475d09a0451ea4b_tara1-p-1600.jpeg"
                  alt="image"
                  width={350}
                  height={250}
                />
                <h2 className="text-xl text-black font-semibold">Tara Na!</h2>
                <p className="text-gray-700 font-semibold">Product Design</p>
              </a>
            </div>
            <div className="cards">
              <a href="https://www.cardines.design/work/jfc-evalues">
                <Image
                  className="rounded-md hover:opacity-90"
                  layout="intrinsic"
                  src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dbfc032cf9fa26a630f20d_jfc-head-p-1600.jpeg"
                  alt="image"
                  width={350}
                  height={250}
                />
                <h2 className="text-xl text-black font-semibold">JFC eValues</h2>
                <p className="text-gray-700 font-semibold">Product Design</p>
              </a>
            </div> 
            <div className="cards">
              <a href="https://www.cardines.design/work/buyinlink">
                <Image
                  className="rounded-md hover:opacity-90"
                  layout="intrinsic"
                  src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dbfcaf3ca8a7b95fba3e4e_buyinlink-01-p-1600.jpeg"
                  alt="image"
                  width={350}
                  height={250}
                />
                <h2 className="text-xl text-black font-semibold">Buyinlink</h2>
                <p className="text-gray-700 font-semibold">Product Design No-Code Dev & Illustration</p>
              </a>
            </div>
            <div className="cards">
              <a href="https://www.cardines.design/work/escuella-taller">
                <Image
                  className="rounded-md hover:opacity-90"
                  layout="intrinsic"
                  src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dc135828b422b2a9e81280_et-header-p-1600.jpeg"
                  alt="image"
                  width={350}
                  height={250}
                />
                <h2 className="text-xl text-black font-semibold">Escuela Taller</h2>
                <p className="text-gray-700 font-semibold">Illustration</p>
              </a>
            </div>
          </div>
        </div>
        <div>
          <div className="p-10 bg-white flex flex-row sm:mx-26 mx-4">
            <h1 className="text-4xl text-black font-semibold mr-5">Certificates</h1>
            <img
              className="hover:animate-blink"
              src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61e00c2a2a617f7c8903f3bf_%E2%9C%A8.png"
              width={40}
              height={40} />
          </div>
          <div className="sm:mx-12 mx-16 sm:grid sm:grid-cols-2 md:grid-cols-3 flex flex-col gap-10">
            <div className="cards">
              <a href="https://www.coursera.org/account/accomplishments/verify/RHU79JWHZ4T2" target="_blank" rel="noreferrer">
                <Image
                  className="rounded-md hover:opacity-90"
                  layout="intrinsic"
                  src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dff66929e13c388dfbe783_1519856558216.jpg"
                  alt="image"
                  width={100}
                  height={100}
                />
                <p className="text-sm text-black font-semibold">California Institute of the Arts</p>
                <h2 className="text-lg text-black font-semibold">Web Design: Strategy and Information Architecture</h2>
                <p className="text-gray-300 text-sm">Nov 2020</p>
              </a>
            </div>
            <div className="cards">
              <a href="https://drive.google.com/file/d/1mz5CXkJJQPTsRB7Za5wk5SEgU1dq-VJN/view" target="_blank" rel="noreferrer">
                <Image
                  className="rounded-md hover:opacity-90"
                  layout="intrinsic"
                  src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dff669e0198a479b5e7b6b_1614813018512.jpg"
                  alt="image"
                  width={100}
                  height={100}
                />
                <p className="text-sm text-black font-semibold">UX+ Conference</p>
                <h2 className="text-lg text-black font-semibold">UX+ Conference 2020</h2>
                <p className="text-gray-300 text-sm">Sep 2020</p>
              </a>
            </div>
            <div className="cards">
              <a href="https://www.coursera.org/account/accomplishments/certificate/U7RJZUC94Q68" target="_blank" rel="noreferrer">
                <Image
                  className="rounded-md hover:opacity-90"
                  layout="intrinsic"
                  src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dff66915a021190b843ab3_1626808053757.jpg"
                  alt="image"
                  width={100}
                  height={100}
                />
                <p className="text-sm text-black font-semibold">University of Minnesota</p>
                <h2 className="text-lg text-black font-semibold">Evaluating User Interfaces</h2>
                <p className="text-gray-300 text-sm">Jul 2020</p>
              </a>
            </div>
            <div className="cards">
              <a href="https://www.coursera.org/account/accomplishments/verify/LJWNMZY8SFF5" target="_blank" rel="noreferrer">
                <Image
                  className="rounded-md hover:opacity-90"
                  layout="intrinsic"
                  src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dff66915a021190b843ab3_1626808053757.jpg"
                  alt="image"
                  width={100}
                  height={100}
                />
                <p className="text-sm text-black font-semibold">University of Minnesota</p>
                <h2 className="text-lg text-black font-semibold">Prototyping & Design</h2>
                <p className="text-gray-300 text-sm">Dec 2019</p>
              </a>
            </div>
            <div className="cards">
              <a href="http://www.graphikamanila.com/uxplus2019coa/TA1159" target="_blank" rel="noreferrer">
                <Image
                  className="rounded-md hover:opacity-90"
                  layout="intrinsic"
                  src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dff669e0198a479b5e7b6b_1614813018512.jpg"
                  alt="image"
                  width={100}
                  height={100}
                />
                <p className="text-sm text-black font-semibold">UX+ Conference</p>
                <h2 className="text-lg text-black font-semibold">UX+ Conference 2019</h2>
                <p className="text-gray-300 text-sm">Sep 2019</p>
              </a>
            </div>
            <div className="cards">
              <a href="https://www.coursera.org/account/accomplishments/verify/B7RB8TG2RXWD" target="_blank" rel="noreferrer">
                <Image
                  className="rounded-md hover:opacity-90"
                  layout="intrinsic"
                  src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dff66915a021190b843ab3_1626808053757.jpg"
                  alt="image"
                  width={100}
                  height={100}
                />
                <p className="text-sm text-black font-semibold">University of Minnesota</p>
                <h2 className="text-lg text-black font-semibold">User Research & Design</h2>
                <p className="text-gray-300 text-sm">Sep 2019</p>
              </a>
            </div>
            <div className="cards">
              <a href="https://www.coursera.org/account/accomplishments/verify/NDBVNUAR4S3X" target="_blank" rel="noreferrer">
                <Image
                  className="rounded-md hover:opacity-90"
                  layout="intrinsic"
                  src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dff66915a021190b843ab3_1626808053757.jpg"
                  alt="image"
                  width={100}
                  height={100}
                />
                <p className="text-sm text-black font-semibold">University of Minnesota</p>
                <h2 className="text-lg text-black font-semibold">Foundations of User Interface Design</h2>
                <p className="text-gray-300 text-sm">Jun 2019</p>
              </a>
            </div>
          </div>
        </div>
      <div className="bg-gray-100 my-32 py-10">
        <div className="mx-20">
        <div className="flex flex-col">
        <div className="flex flex-row items-center">
          <h1 className="text-4xl text-black font-semibold mr-5">Shots</h1>
          <img
            className="hover:animate-bounce"
            src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dffdb4bb525be5d129a80e_%F0%9F%8F%80.svg"
            alt="image"
            width={50}
            height={50} />
        </div>
        <p className="text-gray-600 font-semibold text-lg">Just some designs for when I’m feeling inspired!</p>
        <div className="sm:grid grid-cols-2 flex flex-col gap-10 mt-10">
          <Image
            className="rounded hover:opacity-80"
            layout="responsive"
            alt="image"
            src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dfe4162941d87ce98ff52d_image_processing20201027-4389-14xxh6l.jpg"
            width={200}
            height={150} />
            <Image
            className="rounded hover:opacity-80"
            layout="responsive"
            alt="image"
            src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dfe416051ee2a6270a6e81_image_processing20200908-15996-14uem07.jpg"
            width={200}
            height={150} />
            <Image
            className="rounded hover:opacity-80"
            layout="responsive"
            alt="image"
            src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dfe4161f45cd868e308e83_image_processing20200910-3132-4ee39h.jpg"
            width={200}
            height={150} />
            <Image
            className="rounded hover:opacity-80"
            layout="responsive"
            alt="image"
            src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dfe41736e571eb88797dd2_image_processing20200916-24163-14jfums.jpg"
            width={200}
            height={150} />
            <Image
            className="rounded hover:opacity-80"
            layout="responsive"
            alt="image"
            src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dfe4164e1ac4625e7f9115_image_processing20200912-12777-95ukku.jpg"
            width={200}
            height={150} />
            <Image
            className="rounded hover:opacity-80"
            layout="responsive"
            alt="image"
            src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61dfe4161f45cde067308e82_image_processing20200916-15553-3d68od.jpg"
            width={200}
            height={150} />
        </div>
        </div>
        </div>
      </div>
      <div className="flex items-center justify-center">
      <Image
        className="hover:animate-shake"
        layout="intrinsic"
        alt="image"
        src="https://uploads-ssl.webflow.com/61dbcee9ee276fc3738f48fe/61e00273ee71aa5724239275_Frame%20101%20(2)-p-500.png"
        width={350}
        height={150} />
      </div>
    </div>
  )
}